[1956]
host = "switzerland"
shows = [ "1956-final",]

[1957]
host = "germany"
shows = [ "1957-final",]

[1958]
host = "the-netherlands"
shows = [ "1958-final",]

[1959]
host = "france"
shows = [ "1959-final",]

[1960]
host = "united-kingdom"
shows = [ "1960-final",]

[1961]
host = "france"
shows = [ "1961-final",]

[1962]
host = "luxembourg"
shows = [ "1962-final",]

[1963]
host = "united-kingdom"
shows = [ "1963-final",]

[1964]
host = "denmark"
shows = [ "1964-final",]

[1965]
host = "italy"
shows = [ "1965-final",]

[1966]
host = "luxembourg"
shows = [ "1966-final",]

[1967]
host = "austria"
shows = [ "1967-final",]
