[austria]
english  = 'Austria'
hashtag  = 'AUT'
language = ['german']

[belgium]
english  = 'Belgium'
hashtag  = 'BEL'
language = ['belgian', 'dutch', 'german']

[bulgaria]
english  = 'Bulgaria'
hashtag  = 'BGR'
language = ['bulgarian']

[czechoslovakia]
english = 'Czechoslovakia'
hashtag = 'CSK'
language = ['czechoslovak', 'czech', 'slovak']

[denmark]
english  = 'Denmark'
hashtag  = 'DNK'
language = ['danish', 'faroese', 'greenlandic', 'german']

[finland]
english  = 'Finland'
hashtag  = 'FIN'
language = ['finnish', 'swedish']

[france]
english  = 'France'
hashtag  = 'FRA'
language = ['french']

[germany]
english  = 'Germany'
hashtag  = 'GER'
language = ['german']

[greece]
english  = 'Greece'
hashtag  = 'GRC'
language = ['greek']

[ireland]
english  = 'Ireland'
hashtag  = 'IRL'
language = ['english', 'irish']

[israel]
english  = 'Israel'
hashtag  = 'ISR'
language = ['hebrew']

[italy]
english  = 'Italy'
hashtag  = 'ITA'
language = ['italian']

[luxembourg]
english  = 'Luxembourg'
hashtag  = 'LUX'
language = ['luxembourgish', 'french', 'german']

[monaco]
english  = 'Monaco'
hashtag  = 'MCO'
language = ['french']

[the-netherlands]
english  = 'The Netherlands'
hashtag  = 'NLD'
language = ['dutch']

[norway]
english  = 'Norway'
hashtag  = 'NOR'
language = ['norwegian', 'sami']

[portugal]
english  = 'Portugal'
hashtag  = 'PRT'
language = ['portugese']

[russia]
english  = 'Russia'
hashtag  = 'RUS'
language = ['russian']

[spain]
english  = 'Spain'
hashtag  = 'ESP'
language = ['spanish']

[sweden]
english  = 'Sweden'
hashtag  = 'SWE'
language = ['swedish']

[switzerland]
english  = 'Switzerland'
hashtag  = 'CHE'
language = ['german', 'french', 'italian']

[united-kingdom]
english  = 'United Kingdom'
hashtag  = 'GBR'
language = ['english']

[yugoslavia]
english  = 'Yugoslavia'
hashtag  = 'YUG'
language = ['serbo-croatian', 'slovene', 'macedonian']
