[conny-van-den-bos]
name   = 'Conny Van den bos'
singer = ['conny-van-den-bos']

[kathy-kirby]
name   = 'Kathy Kirby'
singer = ['kathy-kirby']

[butch-moore]
name   = 'Butch Moore'
singer = ['butch-moore']

[ulla-wiesner]
name   = 'Ulla Wiesner'
singer = ['ulla-wiesner']

[kirsti-sparboe]
name   = 'Kirsti Sparboe'
singer = ['kirsti-sparboe']

[lize-marke]
name   = 'Lize Marke'
singer = ['lize-marke']

[marjorie-noel]
name   = 'Marjorie Noël'
singer = ['marjorie-noel']

[ingvar-wixell]
name   = 'Ingvar Wixell'
singer = ['ingvar-wixell']

[guy-mardel]
name   = 'Guy Mardel'
singer = ['guy-mardel']

[simone-de-oliveira]
name   = 'Simone de Oliveira'
singer = ['simone-de-oliveira']

[bobby-solo]
name   = 'Bobby Solo'
singer = ['bobby-solo']

[birgit-bruel]
name   = 'Birgit Brüel'
singer = ['birgit-bruel']

[france-gall]
name   = 'France Gall'
singer = ['france-gall']

[viktor-klimenko]
name   = 'Viktor Klimenko'
singer = ['viktor-klimenko']

[yovanna]
name   = 'Yovanna'
singer = ['yovanna']

