[therese-steinmetz]
name   = 'Thérèse Steinmetz'
singer = ['therese-steinmetz']

[vicky]
name   = 'Vicky'
singer = ['vicky']

[peter-horten]
name   = 'Peter Horten'
singer = ['peter-horten']

[noelle-cordier]
name   = 'Noëlle Cordier'
singer = ['noelle-cordier']

[eduardo-nascimento]
name   = 'Eduardo Nascimento'
singer = ['eduardo-nascimento']

[geraldine]
name   = 'Géraldine'
singer = ['geraldine']

[osten-warnebring]
name   = 'Östen Warnebring'
singer = ['osten-warnebring']

[fredi]
name   = 'Fredi'
singer = ['fredi']

[inge-bruck]
name   = 'Inge Brück'
singer = ['inge-bruck']

[louis-neefs]
name   = 'Louis Neefs'
singer = ['louis-neefs']

[sandie-shaw]
name   = 'Sandie Shaw'
singer = ['sandie-shaw']

[minouche-barelli]
name   = 'Minouche Barelli'
singer = ['minouche-barelli']

[lado-leskovar]
name   = 'Lado Leskovar'
singer = ['lado-leskovar']

[sean-dunphy]
name   = 'Sean Dunphy'
singer = ['sean-dunphy']

