[[austria]]
song   = 'net-als-toen'
points = 6
source = 'jury'

[[austria]]
song   = 'amours-mortes-tant-de-peine'
points = 3
source = 'jury'

[[austria]]
song   = 'all'
points = 1
source = 'jury'

[[belgium]]
song   = 'net-als-toen'
points = 5
source = 'jury'

[[belgium]]
song   = 'la-belle-amour'
points = 2
source = 'jury'

[[belgium]]
song   = 'all'
points = 1
source = 'jury'

[[belgium]]
song   = 'telefon-telefon'
points = 1
source = 'jury'

[[belgium]]
song   = 'corde-della-mia-chitarra'
points = 1
source = 'jury'

[[denmark]]
song   = 'net-als-toen'
points = 3
source = 'jury'

[[denmark]]
song   = 'la-belle-amour'
points = 2
source = 'jury'

[[denmark]]
song   = 'lenfant-que-jetais'
points = 2
source = 'jury'

[[denmark]]
song   = 'straatdeuntje'
points = 2
source = 'jury'

[[denmark]]
song   = 'corde-della-mia-chitarra'
points = 1
source = 'jury'

[[france]]
song   = 'telefon-telefon'
points = 6
source = 'jury'

[[france]]
song   = 'net-als-toen'
points = 4
source = 'jury'

[[germany]]
song   = 'la-belle-amour'
points = 6
source = 'jury'

[[germany]]
song   = 'straatdeuntje'
points = 2
source = 'jury'

[[germany]]
song   = 'net-als-toen'
points = 1
source = 'jury'

[[germany]]
song   = 'lenfant-que-jetais'
points = 1
source = 'jury'

[[italy]]
song   = 'amours-mortes-tant-de-peine'
points = 4
source = 'jury'

[[italy]]
song   = 'skibet-skal-sejle-i-nat'
points = 3
source = 'jury'

[[italy]]
song   = 'net-als-toen'
points = 1
source = 'jury'

[[italy]]
song   = 'telefon-telefon'
points = 1
source = 'jury'

[[italy]]
song   = 'lenfant-que-jetais'
points = 1
source = 'jury'

[[luxembourg]]
song   = 'la-belle-amour'
points = 4
source = 'jury'

[[luxembourg]]
song   = 'net-als-toen'
points = 3
source = 'jury'

[[luxembourg]]
song   = 'all'
points = 1
source = 'jury'

[[luxembourg]]
song   = 'lenfant-que-jetais'
points = 1
source = 'jury'

[[luxembourg]]
song   = 'corde-della-mia-chitarra'
points = 1
source = 'jury'

[[the-netherlands]]
song   = 'skibet-skal-sejle-i-nat'
points = 5
source = 'jury'

[[the-netherlands]]
song   = 'corde-della-mia-chitarra'
points = 2
source = 'jury'

[[the-netherlands]]
song   = 'la-belle-amour'
points = 1
source = 'jury'

[[the-netherlands]]
song   = 'all'
points = 1
source = 'jury'

[[the-netherlands]]
song   = 'wohin-kleines-pony'
points = 1
source = 'jury'

[[switzerland]]
song   = 'net-als-toen'
points = 7
source = 'jury'

[[switzerland]]
song   = 'all'
points = 2
source = 'jury'

[[switzerland]]
song   = 'straatdeuntje'
points = 1
source = 'jury'

[[united-kingdom]]
song   = 'corde-della-mia-chitarra'
points = 2
source = 'jury'

[[united-kingdom]]
song   = 'wohin-kleines-pony'
points = 2
source = 'jury'

[[united-kingdom]]
song   = 'la-belle-amour'
points = 2
source = 'jury'

[[united-kingdom]]
song   = 'skibet-skal-sejle-i-nat'
points = 2
source = 'jury'

[[united-kingdom]]
song   = 'amours-mortes-tant-de-peine'
points = 1
source = 'jury'

[[united-kingdom]]
song   = 'net-als-toen'
points = 1
source = 'jury'
