[[austria]]
song   = 'dors-mon-amour'
points = 7
source = 'jury'

[[austria]]
song   = 'lilla-stjarna'
points = 1
source = 'jury'

[[austria]]
song   = 'nel-blu-dipinto-di-blu'
points = 1
source = 'jury'

[[austria]]
song   = 'fur-zwei-groschen-musik'
points = 1
source = 'jury'

[[belgium]]
song   = 'nel-blu-dipinto-di-blu'
points = 4
source = 'jury'

[[belgium]]
song   = 'giorgio'
points = 2
source = 'jury'

[[belgium]]
song   = 'lilla-stjarna'
points = 1
source = 'jury'

[[belgium]]
song   = 'dors-mon-amour'
points = 1
source = 'jury'

[[belgium]]
song   = 'fur-zwei-groschen-musik'
points = 1
source = 'jury'

[[belgium]]
song   = 'die-ganze-welt-braucht-liebe'
points = 1
source = 'jury'

[[denmark]]
song   = 'dors-mon-amour'
points = 9
source = 'jury'

[[denmark]]
song   = 'ma-petite-chatte'
points = 1
source = 'jury'

[[france]]
song   = 'die-ganze-welt-braucht-liebe'
points = 3
source = 'jury'

[[france]]
song   = 'giorgio'
points = 3
source = 'jury'

[[france]]
song   = 'fur-zwei-groschen-musik'
points = 2
source = 'jury'

[[france]]
song   = 'jeg-rev-et-blad-ud-af-min-dagbog'
points = 1
source = 'jury'

[[france]]
song   = 'nel-blu-dipinto-di-blu'
points = 1
source = 'jury'

[[germany]]
song   = 'ma-petite-chatte'
points = 5
source = 'jury'

[[germany]]
song   = 'nel-blu-dipinto-di-blu'
points = 4
source = 'jury'

[[germany]]
song   = 'dors-mon-amour'
points = 1
source = 'jury'

[[italy]]
song   = 'dors-mon-amour'
points = 6
source = 'jury'

[[italy]]
song   = 'giorgio'
points = 4
source = 'jury'

[[luxembourg]]
song   = 'giorgio'
points = 5
source = 'jury'

[[luxembourg]]
song   = 'lilla-stjarna'
points = 3
source = 'jury'

[[luxembourg]]
song   = 'dors-mon-amour'
points = 1
source = 'jury'

[[luxembourg]]
song   = 'die-ganze-welt-braucht-liebe'
points = 1
source = 'jury'

[[sweden]]
song   = 'giorgio'
points = 4
source = 'jury'

[[sweden]]
song   = 'jeg-rev-et-blad-ud-af-min-dagbog'
points = 1
source = 'jury'

[[sweden]]
song   = 'dors-mon-amour'
points = 1
source = 'jury'

[[sweden]]
song   = 'ma-petite-chatte'
points = 1
source = 'jury'

[[sweden]]
song   = 'fur-zwei-groschen-musik'
points = 1
source = 'jury'

[[sweden]]
song   = 'die-ganze-welt-braucht-liebe'
points = 1
source = 'jury'

[[sweden]]
song   = 'nel-blu-dipinto-di-blu'
points = 1
source = 'jury'

[[switzerland]]
song   = 'lilla-stjarna'
points = 3
source = 'jury'

[[switzerland]]
song   = 'die-ganze-welt-braucht-liebe'
points = 2
source = 'jury'

[[switzerland]]
song   = 'ma-petite-chatte'
points = 1
source = 'jury'

[[switzerland]]
song   = 'heel-de-wereld'
points = 1
source = 'jury'

[[switzerland]]
song   = 'nel-blu-dipinto-di-blu'
points = 1
source = 'jury'

[[switzerland]]
song   = 'dors-mon-amour'
points = 1
source = 'jury'

[[switzerland]]
song   = 'un-grand-amour'
points = 1
source = 'jury'

[[the-netherlands]]
song   = 'giorgio'
points = 6
source = 'jury'

[[the-netherlands]]
song   = 'lilla-stjarna'
points = 2
source = 'jury'

[[the-netherlands]]
song   = 'jeg-rev-et-blad-ud-af-min-dagbog'
points = 1
source = 'jury'

[[the-netherlands]]
song   = 'nel-blu-dipinto-di-blu'
points = 1
source = 'jury'

