[[austria]]
song   = 'non-ho-leta'
points = 5
source = 'jury'

[[austria]]
song   = 'le-chant-de-mallory'
points = 3
source = 'jury'

[[austria]]
song   = 'i-love-the-little-things'
points = 1
source = 'jury'

[[belgium]]
song   = 'non-ho-leta'
points = 5
source = 'jury'

[[belgium]]
song   = 'ou-sont-elles-passees'
points = 3
source = 'jury'

[[belgium]]
song   = 'warum-nur-warum'
points = 1
source = 'jury'

[[denmark]]
song   = 'spiral'
points = 5
source = 'jury'

[[denmark]]
song   = 'laiskotellen'
points = 3
source = 'jury'

[[denmark]]
song   = 'jij-bent-mijn-leven'
points = 1
source = 'jury'

[[finland]]
song   = 'non-ho-leta'
points = 5
source = 'jury'

[[finland]]
song   = 'i-love-the-little-things'
points = 3
source = 'jury'

[[finland]]
song   = 'spiral'
points = 1
source = 'jury'

[[france]]
song   = 'ou-sont-elles-passees'
points = 5
source = 'jury'

[[france]]
song   = 'des-que-le-printemps-revient'
points = 3
source = 'jury'

[[france]]
song   = 'i-love-the-little-things'
points = 1
source = 'jury'

[[germany]]
song   = 'des-que-le-printemps-revient'
points = 5
source = 'jury'

[[germany]]
song   = 'non-ho-leta'
points = 3
source = 'jury'

[[germany]]
song   = 'i-love-the-little-things'
points = 1
source = 'jury'

[[italy]]
song   = 'warum-nur-warum'
points = 5
source = 'jury'

[[italy]]
song   = 'des-que-le-printemps-revient'
points = 3
source = 'jury'

[[italy]]
song   = 'caracola'
points = 1
source = 'jury'

[[luxembourg]]
song   = 'non-ho-leta'
points = 5
source = 'jury'

[[luxembourg]]
song   = 'ou-sont-elles-passees'
points = 3
source = 'jury'

[[luxembourg]]
song   = 'le-chant-de-mallory'
points = 1
source = 'jury'

[[monaco]]
song   = 'le-chant-de-mallory'
points = 5
source = 'jury'

[[monaco]]
song   = 'non-ho-leta'
points = 3
source = 'jury'

[[monaco]]
song   = 'pres-de-ma-riviere'
points = 1
source = 'jury'

[[norway]]
song   = 'i-love-the-little-things'
points = 5
source = 'jury'

[[norway]]
song   = 'laiskotellen'
points = 3
source = 'jury'

[[norway]]
song   = 'sangen-om-dig'
points = 1
source = 'jury'

[[portugal]]
song   = 'non-ho-leta'
points = 5
source = 'jury'

[[portugal]]
song   = 'le-chant-de-mallory'
points = 3
source = 'jury'

[[portugal]]
song   = 'pres-de-ma-riviere'
points = 1
source = 'jury'

[[spain]]
song   = 'warum-nur-warum'
points = 5
source = 'jury'

[[spain]]
song   = 'sangen-om-dig'
points = 3
source = 'jury'

[[spain]]
song   = 'le-chant-de-mallory'
points = 1
source = 'jury'

[[switzerland]]
song   = 'i-love-the-little-things'
points = 5
source = 'jury'

[[switzerland]]
song   = 'non-ho-leta'
points = 3
source = 'jury'

[[switzerland]]
song   = 'ou-sont-elles-passees'
points = 1
source = 'jury'

[[the-netherlands]]
song   = 'non-ho-leta'
points = 5
source = 'jury'

[[the-netherlands]]
song   = 'des-que-le-printemps-revient'
points = 3
source = 'jury'

[[the-netherlands]]
song   = 'i-love-the-little-things'
points = 1
source = 'jury'

[[united-kingdom]]
song   = 'non-ho-leta'
points = 5
source = 'jury'

[[united-kingdom]]
song   = 'laiskotellen'
points = 3
source = 'jury'

[[united-kingdom]]
song   = 'jij-bent-mijn-leven'
points = 1
source = 'jury'

[[yugoslavia]]
song   = 'non-ho-leta'
points = 5
source = 'jury'

[[yugoslavia]]
song   = 'ou-sont-elles-passees'
points = 3
source = 'jury'

[[yugoslavia]]
song   = 'le-chant-de-mallory'
points = 1
source = 'jury'

