[[belgium]]
song   = 'vivo-cantando'
points = 3
source = 'jury'

[[belgium]]
song   = 'primaballerina'
points = 1
source = 'jury'

[[belgium]]
song   = 'bonjour-bonjour'
points = 1
source = 'jury'

[[belgium]]
song   = 'de-troubadour'
points = 1
source = 'jury'

[[belgium]]
song   = 'maman-maman'
points = 1
source = 'jury'

[[belgium]]
song   = 'catherine'
points = 1
source = 'jury'

[[belgium]]
song   = 'desfolhada-portuguesa'
points = 1
source = 'jury'

[[belgium]]
song   = 'pozdrav-svijetu'
points = 1
source = 'jury'

[[finland]]
song   = 'judy-min-van'
points = 3
source = 'jury'

[[finland]]
song   = 'the-wages-of-love'
points = 3
source = 'jury'

[[finland]]
song   = 'bonjour-bonjour'
points = 2
source = 'jury'

[[finland]]
song   = 'boom-bang-a-bang'
points = 1
source = 'jury'

[[finland]]
song   = 'due-grosse-lacrime-bianche'
points = 1
source = 'jury'

[[france]]
song   = 'de-troubadour'
points = 6
source = 'jury'

[[france]]
song   = 'vivo-cantando'
points = 2
source = 'jury'

[[france]]
song   = 'desfolhada-portuguesa'
points = 1
source = 'jury'

[[france]]
song   = 'primaballerina'
points = 1
source = 'jury'

[[germany]]
song   = 'vivo-cantando'
points = 3
source = 'jury'

[[germany]]
song   = 'bonjour-bonjour'
points = 2
source = 'jury'

[[germany]]
song   = 'kuin-silloin-ennen'
points = 1
source = 'jury'

[[germany]]
song   = 'the-wages-of-love'
points = 1
source = 'jury'

[[germany]]
song   = 'catherine'
points = 1
source = 'jury'

[[germany]]
song   = 'boom-bang-a-bang'
points = 1
source = 'jury'

[[germany]]
song   = 'un-jour-un-enfant'
points = 1
source = 'jury'

[[ireland]]
song   = 'un-jour-un-enfant'
points = 4
source = 'jury'

[[ireland]]
song   = 'bonjour-bonjour'
points = 3
source = 'jury'

[[ireland]]
song   = 'kuin-silloin-ennen'
points = 1
source = 'jury'

[[ireland]]
song   = 'due-grosse-lacrime-bianche'
points = 1
source = 'jury'

[[ireland]]
song   = 'vivo-cantando'
points = 1
source = 'jury'

[[italy]]
song   = 'maman-maman'
points = 4
source = 'jury'

[[italy]]
song   = 'de-troubadour'
points = 3
source = 'jury'

[[italy]]
song   = 'boom-bang-a-bang'
points = 3
source = 'jury'

[[luxembourg]]
song   = 'boom-bang-a-bang'
points = 4
source = 'jury'

[[luxembourg]]
song   = 'de-troubadour'
points = 2
source = 'jury'

[[luxembourg]]
song   = 'vivo-cantando'
points = 2
source = 'jury'

[[luxembourg]]
song   = 'kuin-silloin-ennen'
points = 1
source = 'jury'

[[luxembourg]]
song   = 'un-jour-un-enfant'
points = 1
source = 'jury'

[[monaco]]
song   = 'vivo-cantando'
points = 3
source = 'jury'

[[monaco]]
song   = 'catherine'
points = 3
source = 'jury'

[[monaco]]
song   = 'un-jour-un-enfant'
points = 2
source = 'jury'

[[monaco]]
song   = 'de-troubadour'
points = 1
source = 'jury'

[[monaco]]
song   = 'due-grosse-lacrime-bianche'
points = 1
source = 'jury'

[[norway]]
song   = 'judy-min-van'
points = 3
source = 'jury'

[[norway]]
song   = 'jennifer-jennings'
points = 2
source = 'jury'

[[norway]]
song   = 'bonjour-bonjour'
points = 1
source = 'jury'

[[norway]]
song   = 'kuin-silloin-ennen'
points = 1
source = 'jury'

[[norway]]
song   = 'primaballerina'
points = 1
source = 'jury'

[[norway]]
song   = 'de-troubadour'
points = 1
source = 'jury'

[[norway]]
song   = 'vivo-cantando'
points = 1
source = 'jury'

[[portugal]]
song   = 'pozdrav-svijetu'
points = 3
source = 'jury'

[[portugal]]
song   = 'un-jour-un-enfant'
points = 2
source = 'jury'

[[portugal]]
song   = 'vivo-cantando'
points = 2
source = 'jury'

[[portugal]]
song   = 'judy-min-van'
points = 1
source = 'jury'

[[portugal]]
song   = 'boom-bang-a-bang'
points = 1
source = 'jury'

[[portugal]]
song   = 'due-grosse-lacrime-bianche'
points = 1
source = 'jury'

[[spain]]
song   = 'desfolhada-portuguesa'
points = 2
source = 'jury'

[[spain]]
song   = 'primaballerina'
points = 2
source = 'jury'

[[spain]]
song   = 'jennifer-jennings'
points = 2
source = 'jury'

[[spain]]
song   = 'maman-maman'
points = 2
source = 'jury'

[[spain]]
song   = 'kuin-silloin-ennen'
points = 1
source = 'jury'

[[spain]]
song   = 'pozdrav-svijetu'
points = 1
source = 'jury'

[[sweden]]
song   = 'boom-bang-a-bang'
points = 5
source = 'jury'

[[sweden]]
song   = 'maman-maman'
points = 2
source = 'jury'

[[sweden]]
song   = 'un-jour-un-enfant'
points = 1
source = 'jury'

[[sweden]]
song   = 'oj-oj-oj-sa-glad-jeg-skal-bli'
points = 1
source = 'jury'

[[sweden]]
song   = 'the-wages-of-love'
points = 1
source = 'jury'

[[switzerland]]
song   = 'de-troubadour'
points = 4
source = 'jury'

[[switzerland]]
song   = 'the-wages-of-love'
points = 3
source = 'jury'

[[switzerland]]
song   = 'jennifer-jennings'
points = 2
source = 'jury'

[[switzerland]]
song   = 'un-jour-un-enfant'
points = 1
source = 'jury'

[[the-netherlands]]
song   = 'maman-maman'
points = 2
source = 'jury'

[[the-netherlands]]
song   = 'un-jour-un-enfant'
points = 2
source = 'jury'

[[the-netherlands]]
song   = 'judy-min-van'
points = 1
source = 'jury'

[[the-netherlands]]
song   = 'boom-bang-a-bang'
points = 1
source = 'jury'

[[the-netherlands]]
song   = 'the-wages-of-love'
points = 1
source = 'jury'

[[the-netherlands]]
song   = 'kuin-silloin-ennen'
points = 1
source = 'jury'

[[the-netherlands]]
song   = 'catherine'
points = 1
source = 'jury'

[[the-netherlands]]
song   = 'jennifer-jennings'
points = 1
source = 'jury'

[[united-kingdom]]
song   = 'un-jour-un-enfant'
points = 4
source = 'jury'

[[united-kingdom]]
song   = 'jennifer-jennings'
points = 3
source = 'jury'

[[united-kingdom]]
song   = 'bonjour-bonjour'
points = 2
source = 'jury'

[[united-kingdom]]
song   = 'the-wages-of-love'
points = 1
source = 'jury'

[[yugoslavia]]
song   = 'primaballerina'
points = 3
source = 'jury'

[[yugoslavia]]
song   = 'bonjour-bonjour'
points = 2
source = 'jury'

[[yugoslavia]]
song   = 'boom-bang-a-bang'
points = 2
source = 'jury'

[[yugoslavia]]
song   = 'due-grosse-lacrime-bianche'
points = 1
source = 'jury'

[[yugoslavia]]
song   = 'vivo-cantando'
points = 1
source = 'jury'

[[yugoslavia]]
song   = 'catherine'
points = 1
source = 'jury'

