[carlos-mendes]
name        = 'Carlos Eduardo Teixeira Mendes'
known_as    = 'Carlos Mendes'
born        = 1947-05-23
citizenship = ['portugal']

[ronnie-tober]
name        = 'Ronald Edwin Tober'
known_as    = 'Ronnie Tober'
born        = 1945-04-21
citizenship = ['the-netherlands']

[claude-lombard]
name        = 'Claude Lombard'
born        = 1945-02-25
citizenship = ['belgium']

[karel-gott]
name        = 'Karel Gott'
born        = 1939-07-14
died        = 2019-10-01
citizenship = ['czechoslovakia']

[chris-baldo]
name        = 'Christian Baldauff'
known_as    = 'Chris Baldo'
born        = 1943-06-24
died        = 1995-01-24
citizenship = ['luxembourg']

[sophie-garel]
name        = 'Sophie Garel'
born        = 1942-04-22
citizenship = ['france']

[gianni-mascolo]
name        = 'Gianni Mascolo'
born        = 1940-11-03
died        = 2016-12-21
citizenship = ['italy']

[line]
name        = 'Line van Meelen'
known_as    = 'Line'
citizenship = ['france']

[willy]
name        = 'Claude Boillod'
known_as    = 'Willy'
citizenship = ['france']

[claes-goran-hederstrom]
name        = 'Claes-Göran Hederström'
born        = 1945-10-20
citizenship = ['sweden']

[kristina-hautala]
name        = 'Kristina Hautala'
born        = 1948-06-28
citizenship = ['sweden']

[sergio-endrigo]
name        = 'Sergio Endrigo'
born        = 1933-06-15
died        = 2005-09-07
citizenship = ['italy']

[cliff-richard]
name        = 'Harry Rodger Webb'
known_as    = 'Cliff Richard'
born        = 1940-10-14
citizenship = ['united-kingdom']

[odd-brre]
name        = 'Odd Børre Sørensen'
known_as    = 'Odd Børre'
born        = 1939-08-09
citizenship = ['norway']

[pat-mcgeegan]
name        = 'Patrick McGuigan'
known_as    = 'Pat McGeegan'
born        = 1935-02-10
died        = 1987-06-27
citizenship = ['ireland']

[massiel]
name        = 'María de los Ángeles Felisa Santamaría Espinosa'
known_as    = 'Massiel'
born        = 1947-08-02
citizenship = ['spain']

[wencke-myhre]
name        = 'Wenche Synnøve Myhre'
known_as    = 'Wencke Myhre'
born        = 1947-02-15
citizenship = ['norway']

[luci-kapurso]
name        = 'Luciano Capurso'
known_as    = 'Lući Kapurso'
citizenship = ['yugoslavia']

[hamo-hajdarhodzic]
name        = 'Hamo Hajdarhodžić'
citizenship = ['yugoslavia']

