[1956-final]
date         = 1956-05-24
type         = 'final'
performances = [
    'de-vogels-van-holland',
    'das-alte-karussell',
    'messieurs-les-noyes-de-la-seine',
    'im-wartesaal-zum-groen-gluck',
    'le-temps-perdu',
    'ne-crois-pas',
    'aprite-le-finestre',
    'voorgoed-voorbij',
    'refrain',
    'le-plus-beau-jour-de-ma-vie',
    'so-geht-das-jede-nacht',
    'il-est-la',
    'les-amants-de-minuit',
    'amami-se-vuoi',
]
