[1957-final]
date         = 1957-03-03
type         = 'final'
performances = [
    'straatdeuntje',
    'amours-mortes-tant-de-peine',
    'all',
    'corde-della-mia-chitarra',
    'wohin-kleines-pony',
    'net-als-toen',
    'telefon-telefon',
    'la-belle-amour',
    'skibet-skal-sejle-i-nat',
    'lenfant-que-jetais',
]
