[1958-final]
date = 1958-03-12
type = 'final'
performances = [
    'nel-blu-dipinto-di-blu',
    'heel-de-wereld',
    'dors-mon-amour',
    'un-grand-amour',
    'lilla-stjarna',
    'jeg-rev-et-blad-ud-af-min-dagbog',
    'ma-petite-chatte',
    'fur-zwei-groschen-musik',
    'die-ganze-welt-braucht-liebe',
    'giorgio',
]
