[1959-final]
date         = 1959-03-11
type         = 'final'
performances = [
    'oui-oui-oui-oui',
    'uh-jeg-ville-nske-jeg-var-dig',
    'piove',
    'mon-ami-pierrot',
    'een-beetje',
    'heut-wolln-wir-tanzen-gehn',
    'augustin',
    'irgendwoher',
    'der-k-und-k-kalypso-aus-wien',
    'sing-little-birdie',
    'hou-toch-van-mij',
]
