[1960-final]
date         = 1960-01-01
type         = 'final'
performances = [
    'looking-high-high-high',
    'alla-andra-far-varann',
    'so-laang-wes-du-do-bast',
    'det-var-en-yndig-tid',
    'mon-amour-pour-toi',
    'voi-voi',
    'du-hast-mich-so-fasziniert',
    'ce-soir-la',
    'cielo-e-terra',
    'wat-een-geluk',
    'bonne-nuit-ma-cherie',
    'romantica',
    'tom-pillibi',
]
