[1961-final]
date         = 1961-03-18
type         = 'final'
performances = [
    'estando-contigo',
    'allons-allons-les-enfants',
    'sehnsucht',
    'valoa-ikkunassa',
    'neke-davne-zvezde',
    'wat-een-dag',
    'april-april',
    'einmal-sehen-wir-uns-wieder',
    'printemps-avril-carillonne',
    'nous-aurons-demain',
    'september-gouden-roos',
    'sommer-i-palma',
    'angelique',
    'nous-les-amoureux',
    'are-you-sure',
    'al-di-la',
]
