[1962-final]
date         = 1962-01-01
type         = 'final'
performances = [
    'tipi-tii',
    'ton-nom',
    'llamame',
    'nur-in-der-wiener-luft',
    'vuggevise',
    'sol-och-var',
    'zwei-kleine-italiener',
    'katinka',
    'un-premier-amour',
    'kom-sol-kom-regn',
    'le-retour',
    'ne-pali-svetlo-u-sumrak',
    'ring-a-ding-girl',
    'petit-bonhomme',
    'addio-addio',
    'dis-rien',
]
