[1963-final]
date         = 1963-01-01
type         = 'final'
performances = [
    'say-wonderful-things',
    'een-speeldoos',
    'marcel',
    'vielleicht-geschieht-ein-wunder',
    'solhverv',
    'uno-per-tutte',
    'muistojeni-laulu',
    'dansevise',
    'brodovi',
    'ten-va-pas',
    'elle-etait-si-jolie',
    'algo-prodigioso',
    'en-gang-i-stockholm',
    'waarom',
    'lamour-sen-va',
    'a-force-de-prier',
]
