[1964-final]
date         = 1964-01-01
type         = 'final'
performances = [
    'des-que-le-printemps-revient',
    'jij-bent-mijn-leven',
    'spiral',
    'sangen-om-dig',
    'laiskotellen',
    'warum-nur-warum',
    'le-chant-de-mallory',
    'i-love-the-little-things',
    'man-gewohnt-sich-so-schnell-an-das-schone',
    'ou-sont-elles-passees',
    'oracao',
    'non-ho-leta',
    'zivot-je-sklopio-krug',
    'i-miei-pensieri',
    'pres-de-ma-riviere',
    'caracola',
]
