[1965-final]
date         = 1965-01-01
type         = 'final'
performances = [
    't-is-genoeg',
    'i-belong',
    'que-bueno-que-bueno',
    'im-walking-the-streets-in-the-rain',
    'paradies-wo-bist-du',
    'sag-ihr-ich-lass-sie-gruen',
    'karusell',
    'als-het-weer-lente-is',
    'va-dire-a-lamour',
    'absent-friend',
    'navoue-jamais',
    'sol-de-inverno',
    'se-piangi-se-ridi',
    'for-din-skyld',
    'poupee-de-cire-poupee-de-son',
    'aurinko-laskee-lanteen',
    'ceznja',
    'non-a-jamais-sans-toi',
]

