[1966-final]
date         = 1966-01-01
type         = 'final'
performances = [
    'die-zeiger-der-uhr',
    'stop-ja-stop-ja-stop-mens-legen-er-go',
    'un-peu-de-poivre-un-peu-de-sel',
    'ce-soir-je-tattendais',
    'brez-besed',
    'intet-er-nytt-under-solen',
    'play-boy',
    'ele-e-ela',
    'merci-cherie',
    'nygammal-vals-eller-hip-man-svinaherde',
    'yo-soy-aquel',
    'ne-vois-tu-pas',
    'bien-plus-fort',
    'dio-come-ti-amo',
    'chez-nous',
    'fernando-en-philippo',
    'come-back-to-stay',
    'a-man-without-love',
]

