[1967-final]
date         = 1967-01-01
type         = 'final'
performances = [
    'ring-dinge',
    'lamour-est-bleu',
    'warum-es-hunderttausend-sterne-gibt',
    'il-doit-faire-beau-la-bas',
    'o-vento-mudou',
    'quel-coeur-vas-tu-briser',
    'som-en-drom',
    'varjoon-suojaan',
    'anouschka',
    'ik-heb-zorgen',
    'puppet-on-a-string',
    'hablemos-del-amor',
    'dukkemann',
    'boum-badaboum',
    'vse-roze-sveta',
    'non-andare-piu-lontano',
    'if-i-could-choose',
]

