[1968-final]
date         = 1968-01-01
type         = 'final'
performances = [
    'verao',
    'morgen',
    'quand-tu-reviendras',
    'tausend-fenster',
    'nous-vivrons-damour',
    'guardando-il-sole',
    'a-chacun-sa-chanson',
    'det-borjar-verka-karlek-banne-mej',
    'kun-kello-kay',
    'la-source',
    'marianne',
    'congratulations',
    'stress',
    'chance-of-a-lifetime',
    'la-la-la',
    'ein-hoch-der-liebe',
    'jedan-dan',
]

