[1969-final]
date         = 1969-01-01
type         = 'final'
performances = [
    'pozdrav-svijetu',
    'catherine',
    'vivo-cantando',
    'maman-maman',
    'the-wages-of-love',
    'due-grosse-lacrime-bianche',
    'boom-bang-a-bang',
    'de-troubadour',
    'judy-min-van',
    'jennifer-jennings',
    'bonjour-bonjour',
    'oj-oj-oj-sa-glad-jeg-skal-bli',
    'primaballerina',
    'un-jour-un-enfant',
    'desfolhada-portuguesa',
    'kuin-silloin-ennen',
]

