[straatdeuntje]
title   = 'Straatdeuntje'
artist  = 'bobbejaan-choepen'
country = 'belgium'

[amours-mortes-tant-de-peine]
title   = 'Amours mortes (tant de peine)'
artist  = 'daniele-dupre'
country = 'luxembourg'

[all]
title   = 'All'
artist  = 'patricia-bredin'
country = 'united-kingdom'

[corde-della-mia-chitarra]
title   = 'Corde della mia chitarra'
artist  = 'nunzio-gallo'
country = 'italy'

[wohin-kleines-pony]
title   = 'Wohin, kleines Pony?"'
artist  = 'bob-martin'
country = 'austria'

[net-als-toen]
title   = 'Net als toen'
artist  = 'corry-brokken'
country = 'the-netherlands'

[telefon-telefon]
title   = 'Telefon, Telefon'
artist  = 'margot-hielscher'
country = 'germany'

[la-belle-amour]
title   = 'La belle amour'
artist  = 'paule-desjardins'
country = 'france'

[skibet-skal-sejle-i-nat]
title   = 'Skibet skal sejle i nat'
artist  = 'birthe-wilke-gustav-winckler'
country = 'denmark'

[lenfant-que-jetais]
title   = "L'enfant que j'étais"
artist  = 'lys-assia'
country = 'switzerland'
