[straatdeuntje]
title    = 'Straatdeuntje'
artist   = 'bobbejaan-choepen'
country  = 'belgium'
language = ['dutch']

[amours-mortes-tant-de-peine]
title    = 'Amours mortes (tant de peine)'
artist   = 'daniele-dupre'
country  = 'luxembourg'
language = ['french']

[all]
title    = 'All'
artist   = 'patricia-bredin'
country  = 'united-kingdom'
language = ['english']

[corde-della-mia-chitarra]
title    = 'Corde della mia chitarra'
artist   = 'nunzio-gallo'
country  = 'italy'
language = ['italian']

[wohin-kleines-pony]
title    = 'Wohin, kleines Pony?"'
artist   = 'bob-martin'
country  = 'austria'
language = ['german']

[net-als-toen]
title    = 'Net als toen'
artist   = 'corry-brokken'
country  = 'the-netherlands'
language = ['dutch']

[telefon-telefon]
title    = 'Telefon, Telefon'
artist   = 'margot-hielscher'
country  = 'germany'
language = ['german']

[la-belle-amour]
title    = 'La belle amour'
artist   = 'paule-desjardins'
country  = 'france'
language = ['french']

[skibet-skal-sejle-i-nat]
title    = 'Skibet skal sejle i nat'
artist   = 'birthe-wilke-gustav-winckler'
country  = 'denmark'
language = ['danish']

[lenfant-que-jetais]
title    = "L'enfant que j'étais"
artist   = 'lys-assia'
country  = 'switzerland'
language = ['french']
