[nel-blu-dipinto-di-blu]
title    = "Nel Blu Dipinto Di Blu"
artist   = 'domenico-modugno'
country  = 'italy'
language = ['italian']

[heel-de-wereld]
title    = "Heel De Wereld"
artist   = 'corry-brokken'
country  = 'the-netherlands'
language = ['dutch']

[dors-mon-amour]
title    = "Dors Mon Amour"
artist   = 'andre-claveau'
country  = 'france'
language = ['french']

[un-grand-amour]
title    = "Un Grand Amour"
artist   = 'solange-berry'
country  = 'luxembourg'
language = ['french']

[lilla-stjarna]
title    = "Lilla Stjärna"
artist   = 'alice-babs'
country  = 'sweden'
language = ['swedish']

[jeg-rev-et-blad-ud-af-min-dagbog]
title    = "Jeg Rev Et Blad Ud Af Min Dagbog"
artist   = 'raquel-rastenni'
country  = 'denmark'
language = ['danish']

[ma-petite-chatte]
title    = "Ma Petite Chatte"
artist   = 'fud-leclerc'
country  = 'belgium'
language = ['french']

[fur-zwei-groschen-musik]
title    = "Für Zwei Groschen Musik"
artist   = 'margot-hielscher'
country  = 'germany'
language = ['german']

[die-ganze-welt-braucht-liebe]
title    = "Die Ganze Welt Braucht Liebe"
artist   = 'liane-augustin'
country  = 'austria'
language = ['german']

[giorgio]
title    = "Giorgio"
artist   = 'lys-assia'
country  = 'switzerland'
language = ['german', 'italian']
