[des-que-le-printemps-revient]
title    = "Dès Que Le Printemps Revient"
artist   = 'hugues-aufray'
country  = 'luxembourg'
language = ['french']

[jij-bent-mijn-leven]
title    = "Jij Bent Mijn Leven"
artist   = 'anneke-gronloh'
country  = 'the-netherlands'
language = ['dutch']

[spiral]
title    = "Spiral"
artist   = 'arne-bendiksen'
country  = 'norway'
language = ['norwegian']

[sangen-om-dig]
title    = "Sangen Om Dig"
artist   = 'bjrn-tidmand'
country  = 'denmark'
language = ['danish']

[laiskotellen]
title    = "Laiskotellen"
artist   = 'lasse-martenson'
country  = 'finland'
language = ['finnish']

[warum-nur-warum]
title    = "Warum Nur, Warum?"
artist   = 'udo-jurgens'
country  = 'austria'
language = ['german']

[le-chant-de-mallory]
title    = "Le Chant De Mallory"
artist   = 'rachel'
country  = 'france'
language = ['french']

[i-love-the-little-things]
title    = "I Love The Little Things"
artist   = 'matt-monro'
country  = 'united-kingdom'
language = ['english']

[man-gewohnt-sich-so-schnell-an-das-schone]
title    = "Man Gewöhnt Sich So Schnell An Das Schöne"
artist   = 'nora-nova'
country  = 'germany'
language = ['german']

[ou-sont-elles-passees]
title    = "Où Sont-elles Passées?"
artist   = 'romuald'
country  = 'monaco'
language = ['french']

[oracao]
title    = "Oração"
artist   = 'antonio-calvario'
country  = 'portugal'
language = ['portugese']

[non-ho-leta]
title    = "Non Ho L'étà"
artist   = 'gigliola-cinquetti'
country  = 'italy'
language = ['italian']

[zivot-je-sklopio-krug]
title    = "Zivot Je Sklopio Krug"
artist   = 'sabahudin-kurt'
country  = 'yugoslavia'
language = ['serbo-croatian']

[i-miei-pensieri]
title    = "I Miei Pensieri"
artist   = 'anita-traversi'
country  = 'switzerland'
language = ['italian']

[pres-de-ma-riviere]
title    = "Près De Ma Rivière"
artist   = 'robert-cogoi'
country  = 'belgium'
language = ['french']

[caracola]
title    = "Caracola"
artist   = 'tim-nelly-and-tony'
country  = 'spain'
language = ['spanish']
