[die-zeiger-der-uhr]
title    = "Die Zeiger Der Uhr"
artist   = 'margot-eskens'
country  = 'germany'
language = ['german']

[stop-ja-stop-ja-stop-mens-legen-er-go]
title    = "Stop, Ja Stop - Ja Stop, Mens Legen Er Go"
artist   = 'ulla-pia'
country  = 'denmark'
language = ['danish']

[un-peu-de-poivre-un-peu-de-sel]
title    = "Un Peu De Poivre, Un Peu De Sel"
artist   = 'tonia'
country  = 'belgium'
language = ['french']

[ce-soir-je-tattendais]
title    = "Ce Soir Je T'attendais"
artist   = 'michele-torr'
country  = 'luxembourg'
language = ['french']

[brez-besed]
title    = "Brez Besed"
artist   = 'berta-ambroz'
country  = 'yugoslavia'
language = ['slovene']

[intet-er-nytt-under-solen]
title    = "Intet Er Nytt Under Solen"
artist   = 'ase-kleveland'
country  = 'norway'
language = ['norwegian']

[play-boy]
title    = "Play-boy"
artist   = 'ann-christine-nystrom'
country  = 'finland'
language = ['finnish']

[ele-e-ela]
title    = "Ele E Ela"
artist   = 'madalena-iglesias'
country  = 'portugal'
language = ['portugese']

[merci-cherie]
title    = "Merci Chérie"
artist   = 'udo-jurgens'
country  = 'austria'
language = ['german', 'french']

[nygammal-vals-eller-hip-man-svinaherde]
title    = "Nygammal Vals Eller Hip Man Svinaherde"
artist   = 'lill-lindfors-and-svante-thuresson'
country  = 'sweden'
language = ['swedish']

[yo-soy-aquel]
title    = "Yo Soy Aquél"
artist   = 'raphael'
country  = 'spain'
language = ['spanish']

[ne-vois-tu-pas]
title    = "Ne Vois-tu Pas?"
artist   = 'madeleine-pascal'
country  = 'switzerland'
language = ['french']

[bien-plus-fort]
title    = "Bien Plus Fort"
artist   = 'tereza'
country  = 'monaco'
language = ['french']

[dio-come-ti-amo]
title    = "Dio Come Ti Amo"
artist   = 'domenico-modugno'
country  = 'italy'
language = ['italian']

[chez-nous]
title    = "Chez Nous"
artist   = 'dominique-walter'
country  = 'france'
language = ['french']

[fernando-en-philippo]
title    = "Fernando En Philippo"
artist   = 'milly-scott'
country  = 'the-netherlands'
language = ['dutch']

[come-back-to-stay]
title    = "Come Back To Stay"
artist   = 'dickie-rock'
country  = 'ireland'
language = ['english']

[a-man-without-love]
title    = "A Man Without Love"
artist   = 'kenneth-mckellar'
country  = 'united-kingdom'
language = ['english']

