name: Run tests

on:
  push:

jobs:
  tests:
    name: Run the tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Test with pytest
        run: |
          pip install pytest
          pytest -v
